# -*- coding: utf-8 -*-
"""Build data + dish images for the menu.

Reads data/*.json (prices synced from qlub by tools/qlub-sync.py), finds each dish's background-free
cutout in the project's "صور المنيو - بدون خلفية" folder (local only, not in git), trims it to the
subject, and writes WebP (full 760px + card 380px) to assets/dishes/. Emits data/menu.js (window.MENU).
Both outputs are committed; the Pages workflow only copies files, it does not run this.

Run:  python tools/build.py
"""
import os, re, sys, json, hashlib
from PIL import Image

sys.stdout.reconfigure(encoding='utf-8')
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OLD = ROOT   # data/ and tools/sources.json live in this repo
CUT = r'C:\Users\Owner\Desktop\شغل كلود\المطاعم - التسويق\لا كابانا\صور المنيو - بدون خلفية'
OUT_IMG = os.path.join(ROOT, 'assets', 'dishes')
os.makedirs(OUT_IMG, exist_ok=True)

load = lambda p: json.load(open(p, encoding='utf-8'))
menu = load(os.path.join(OLD, 'data', 'menu.json'))['dishes']
cats = sorted(load(os.path.join(OLD, 'data', 'categories.json')), key=lambda c: c['order'])
src = load(os.path.join(OLD, 'tools', 'sources.json'))
prices = load(os.path.join(OLD, 'data', 'prices.json'))
brand = load(os.path.join(OLD, 'data', 'brand.json'))
clean = lambda s: re.sub(r'\s+', ' ', re.sub(r'[\\/:*?"<>|]', ' - ', s)).strip(' .-')

DRINKS = {'hot-drinks', 'cold-drinks', 'juices', 'mojito', 'soft-drinks', 'wine', 'shisha'}
LISTS = {'shisha', 'wine'}            # compact rows, no photos
SIZES = (('', 760), ('-sm', 380))

def export(cut_path, key):
    """Trim the transparent cutout to its subject and write full + small WebP. Returns aspect ratio (w/h)."""
    im = Image.open(cut_path).convert('RGBA')
    bb = im.split()[3].point(lambda a: 255 if a > 10 else 0).getbbox()
    if bb:
        pad = int(max(bb[2] - bb[0], bb[3] - bb[1]) * 0.03)
        im = im.crop((max(0, bb[0] - pad), max(0, bb[1] - pad), min(im.width, bb[2] + pad), min(im.height, bb[3] + pad)))
    for suf, size in SIZES:
        dst = os.path.join(OUT_IMG, f'{key}{suf}.webp')
        t = im.copy(); t.thumbnail((size, size), Image.LANCZOS)
        t.save(dst, 'WEBP', quality=82, method=6, alpha_quality=90)
    return round(im.width / im.height, 3)

out_cats, n_img, seen = [], 0, {}
ci = 0
for c in cats:
    items = [d for d in menu if d['category'] == c['id'] and d.get('available', True)]
    if not items: continue
    has_img = any(src.get(d.get('image', d['id'])) for d in items)
    if has_img: ci += 1
    folder = f"{ci:02d} {clean(c['label']['ar'])}"
    dishes, n = [], 0
    for d in [x for x in menu if x['category'] == c['id']]:
        p = src.get(d.get('image', d['id']))
        cut = None
        if p and os.path.exists(p):
            n += 1
            cut = os.path.join(CUT, folder, f"{n:02d} {clean(d['name']['ar'])}.png")
        if not d.get('available', True): continue
        img = ratio = None
        if cut and os.path.exists(cut) and c['id'] not in LISTS:
            h = hashlib.md5(open(cut, 'rb').read()).hexdigest()[:10]
            if h not in seen: seen[h] = (d['id'], export(cut, d['id'])); n_img += 1
            img, ratio = seen[h]
        desc = d.get('description') or {}
        dishes.append({k: v for k, v in {
            'id': d['id'], 'ar': d['name']['ar'], 'en': d['name']['en'],
            'dar': desc.get('ar', ''), 'den': desc.get('en', ''),
            'price': prices.get(d['id']), 'img': img, 'ratio': ratio,
            'veg': bool(d.get('vegetarian')), 'spicy': bool(d.get('spicy')), 'sig': bool(d.get('signature')),
            'cal': d.get('calories') or None}.items() if v not in (None, False, '')})
    out_cats.append({'id': c['id'], 'ar': c['label']['ar'], 'en': c['label']['en'],
                     'sar': c.get('intro', {}).get('subtitle', {}).get('ar', ''),
                     'sen': c.get('intro', {}).get('subtitle', {}).get('en', ''),
                     'kind': 'list' if c['id'] in LISTS else 'drink' if c['id'] in DRINKS else 'food', 'items': dishes})

data = {'brand': {'ar': brand['name']['ar'], 'en': brand['name']['en'], 'tagAr': brand['tagline']['ar'],
                  'tagEn': brand['tagline']['en'], 'cityAr': brand['location']['ar'], 'cityEn': brand['location']['en']},
        'categories': out_cats}
with open(os.path.join(ROOT, 'data', 'menu.js'), 'w', encoding='utf-8') as f:
    f.write('/* generated by tools/build.py — do not edit by hand */\nwindow.MENU = ')
    json.dump(data, f, ensure_ascii=False, separators=(',', ':'))
    f.write(';\n')
tot = sum(len(c['items']) for c in out_cats)
print(f'{len(out_cats)} sections, {tot} items, {n_img} images')
